theme: jekyll-theme-cayman
title: Open Research Calendar
description: A community tool to gather all Open Research events in one place
google_analytics: G-VNGZLTVBTP
github:
  is_project_page: true
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: "Documents/**"
    values:
      sitemap: false 
exclude:
  - Publicity/
